version: '3.6'

services:
  percona:
    image: percona:8
    ports:
      - "3306:3306"
    env_file: configuration.env
    volumes:
      - percona:/var/lib/mysql

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    env_file: configuration.env
    volumes:
      - postgres:/var/lib/postgresql/data/pgdata

volumes:
  percona:
    driver: local
  postgres:
    driver: local